#!/usr/bin/env bash
# a Bash script that configures and install nginx

sudo apt-get update -y
sudo apt-get nginx -y
ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
