#!/usr/bin/env bash
# a Bash script that configures and install nginx

sudo apt-get update -y
sudo apt-get nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
