#!/usr/bin/env bash
# display number from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

var1="bad luck from China"
var2="bad luck from Japan"
var3="bad luck from Italy"
i=1
while [ $i -lt 21 ]; do
	case $i in
		4)
			echo "$i" && echo "$var1"
			;;
		9)
			echo "$i" && echo "$var2"
			;;
		17)
			echo "$i" && echo "$var3"
			;;
		*)
			echo "$i"
			;;
	esac
  	((i++))
done
